services:
  forti:
    build: .
    hostname: forti
    container_name: forti
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config/openfortivpn.config:/etc/openfortivpn/config:ro
      - ./config/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
      - ./logs/tinyproxy/:/var/log/tinyproxy/
    devices:
      - /dev/ppp:/dev/ppp
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888
